### ISSUE TITLE
youtube video and streams now completely don't work nothing will load

### ISSUE THREAD

**Issue by AzzyDR** [WaterMediaTeam/watermedia#103]
the only thing that will load is google drive

![2024-09-24_22 23 45](https://github.com/user-attachments/assets/0c205584-4a2f-42f3-84d9-e2c4a3abf9d9)
![2024-09-24_22 23 46](https://github.com/user-attachments/assets/e8c582dd-a6a5-4639-b00f-f2449e816a59)

**Comment by AzzyDR** [comment]
i have tried like 8 videos/streams

**Comment by PainterShock** [comment]
i'm also having this issue on my server, none of us can play youtube videos anymore suddenly

**Comment by AzzyDR** [comment]
> i'm also having this issue on my server, none of us can play youtube videos anymore suddenly

https://github.com/WaterMediaTeam/watermedia/issues/92

its been an issue apparently but now its completely broken

its supposed to be fixed in the next update

**Comment by PainterShock** [comment]
well lets hope for the best on that

**Comment by SrRapero720** [comment]
stop making duplocated of issues
i am aware and #92 is the place
