### ISSUE TITLE
"Watermedia has failed to load correctly". 

### ISSUE THREAD

**Issue by LucasPersonS** [WaterMediaTeam/watermedia#105]
I am currently using Curseforge to load my modpack, and this is the log:
[crash-2024-09-30_18.41.32-fml.txt](https://github.com/user-attachments/files/17196739/crash-2024-09-30_18.41.32-fml.txt)

**Comment by SrRapero720** [comment]
Caused by 1: java.lang.RuntimeException: Failed starting WATERMeDIA for Forge: TLauncher is NOT supported by WATERMeDIA, please stop using it (and consider safe alternatives like SKLauncher or MultiMC)

**DO NOT USE TLAUNCHER, THANKS**

**Comment by LucasPersonS** [comment]
I am not using tlauncher :) I'm using Curseforge

**Comment by SrRapero720** [comment]
remove TL skin cape then
