### ISSUE TITLE
1.12.2 all Versions was deleted???

### ISSUE THREAD

**Issue by Mike74846** [WaterMediaTeam/watermedia#107]
Hi,
I have see the last 2 versions with 1.12.2 Support was deleted from CurseForge and Modrinth. Why have you this make?
I have love this mod but 1.12.2 was my version. I hope you can give me a little statement

**Comment by SrRapero720** [comment]
1. I am not providing support
2. Watermedia causes a bunch of issues on other signed jar mods (not blaming watermedia, blaming the signed jar)

I preffer avoid more bug reports about 1.12.2 and people complain about classloading issues and of course prevent users start blaming other modders
