### ISSUE TITLE
Version 2.1.0 alpha 5 on fabric crashes on startup

### ISSUE THREAD

**Issue by Gamiseus** [WaterMediaTeam/watermedia#108]
Alpha 4 loads fine, even in my modpack with some 500 mods. Tested alpha 5 on it's own to be sure, can't get it to launch. No crash report generated unless it was in my modpack, but the report in the modpack was the exact error reported in my latest.log here with no further context. I tested multiple versions of fabric loader as well, no dice.

https://pastebin.com/tqFAKNqP

**Comment by SrRapero720** [comment]
pretty sure you should _NOT_ be using alpha versions if you're not sure what are you doing

Alpha is for the v2.1.x of WATERMeDIA, a **BREAKING CHANGE** update. no mods (even waterframes) are working with the alpha
