### ISSUE TITLE
Mac is garbage

### ISSUE THREAD

**Issue by AntoNipples** [WaterMediaTeam/watermedia#112]
I followed the instructions and downloaded VLC on Mac OS but the tv still wont work on this 1.20.1 server i am in, if i am doing something wrong can please tell me

**Comment by SrRapero720** [comment]
can try latest watermedia version? i founded a bug that cause some issues on the binary discovery

**Comment by SrRapero720** [comment]
extra: i confirm mac is garbage

**Comment by AntoNipples** [comment]
it works now thank you sir
