### ISSUE TITLE
Windows defender is flaging your mod as a virus

### ISSUE THREAD

**Issue by Goldocelot** [WaterMediaTeam/watermedia#115]
Hello,

I don't know what happened but it seem that now microsoft defender detect your mod as a virus.

It was not detected yesterday.

I attached you a screenshot, i'm sorry it is in french as my computer is in french.

![image](https://github.com/user-attachments/assets/dc8932ff-a513-40f0-8b58-02a2f1f20909)

**Comment by SrRapero720** [comment]
Its a false positive, we already receive some reports in the past about it (including for other mods).
https://www.reddit.com/r/feedthebeast/comments/1bh833v/a_possible_threat_trojan_detection_please_help/

Just to clarify, watermedia and its releases are safe, all versions are released via github and source code is also public, so there's no threats about.
