### ISSUE TITLE
Watermedia is incompatible with Xenon.

### ISSUE THREAD

**Issue by Aleccolin** [WaterMediaTeam/watermedia#118]
When loading up Watermedia with Xenon it says its not Compatible.

[crash-2024-12-18_20.25.45-fml.txt](https://github.com/user-attachments/files/18187983/crash-2024-12-18_20.25.45-fml.txt)
[latest.log](https://github.com/user-attachments/files/18187986/latest.log)

![image](https://github.com/user-attachments/assets/47a4d9fb-b4fb-4e28-9aed-44a5fcb984d0)

**Comment by SrRapero720** [comment]
this was removed in newer versions.
despite that, do not use xenon
