### ISSUE TITLE
Issue with watermedia loading on waterframes.

### ISSUE THREAD

**Issue by FatalLuck** [WaterMediaTeam/watermedia#119]
Hi I'm unable to see anything that's posted on waterframes tvs it just comes up with a orange background saying Failed to Load VLC This is not normal behaviour report it to watermedia author.
![Issue](https://github.com/user-attachments/assets/763be0ae-636d-41ff-8e3d-23762801a7c5)

**Comment by SrRapero720** [comment]
send logs

**Comment by FatalLuck** [comment]
[Uploading latest.log…]()

**Comment by SrRapero720** [comment]
you need to wait until the log finish uploading

**Comment by FatalLuck** [comment]
[latest.log](https://github.com/user-attachments/files/18202542/latest.log)

**Comment by SrRapero720** [comment]
go to `C:\Users\ellio\AppData\Local\Temp\watermedia\` and delete the folder `videolan`

**Comment by FatalLuck** [comment]
Thank you that has fixed the issue.
