### ISSUE TITLE
Sounds of videos are very loud when logging into the world

### ISSUE THREAD

**Issue by azdelux** [WaterMediaTeam/watermedia#12]
I play on a Solo World in 1.20.1 and when I join my world, every sounds of the videos play at the sametime and with the volume at maximum.
Same thing when I switch from nether to overworld

**Comment by azdelux** [comment]
its like the sound is not only in the range I want to, and boosted at 200%

**Comment by SrRapero720** [comment]
Transfered to watermedia because this issue come from this mod
