### ISSUE TITLE
Crash when playing video

### ISSUE THREAD

**Issue by eldediamante** [WaterMediaTeam/watermedia#15]
- ESP 
```
- Entro al server.
- Ejecuto el comando: "/playvideo @a 50 https://youtu.be/lIe4VHXpftg"
- Y crashea (Cierre completo del minecraft) 
```
- ENG 
```
- I enter the server.
- I run the command: "/playvideo @a 50 https://youtu.be/lIe4VHXpftg"
- And it crashes (Complete closure of minecraft)
```
Version Minecraft: Forge - 40.2.10 -> **1.18.2**
Version Mod: 1.2.0 - 1.2.16 - 1.3.0 - 1.3.20 - 1.3.22 - 1.3.23
And "Video Player mod": [2.20](https://www.curseforge.com/minecraft/mc-mods/video-player/files/4628952)
Error:
![imagen_2023-07-29_223019769](https://github.com/SrRapero720/watermedia/assets/55103304/675be51c-1142-48b1-85fa-286a28a8d5cf)
Crash log: [crash-2023-07-29_22.29.29-client.txt](https://github.com/SrRapero720/watermedia/files/12207937/crash-2023-07-29_22.29.29-client.txt)

**Comment by SrRapero720** [comment]
videoplayer is on a broken state
i can't help to goedix to fix it, i am busy updating watermedia and my own mod, maintain everything is heavy.
wait until goedix got back and launch a huge fix

btw is a videoplayer issue, not a watermedia one.
