### ISSUE TITLE
Watermedia 2.0 alpha - Waterframes version

### ISSUE THREAD

**Issue by bazmetal** [WaterMediaTeam/watermedia#16]
Hi SrRapero,

What version of Waterframes works with the new Watermedia 2.0 you made?

I have tried Waterframes 1.3.1e and 1.4.1a, both of them are incompatible, they show that error message.

**Comment by SrRapero720** [comment]
watermedia alpha is just that, an alpha.
is a fresh version with internal breaking changes. that version was published just for developers.
Please use watermedia 1.3.x

and that version of watermedia is gonna begin used for waterframes 2.x and right now is on closed alpha

**Comment by bazmetal** [comment]
Ah ok, thanks for the explanation :)
