### ISSUE TITLE
1.19.2 mod not detecting my OS (macbook m1 silicon)

### ISSUE THREAD

**Issue by Decryptu** [WaterMediaTeam/watermedia#20]
Hello ! I'm having trouble running the game with a recent java 17 (17.0.8) version on **MC 1.19.2 with Forge**, it only works if I use old java 17 versions. Problem is, minecraft keeps crashing on M1 processors (MacOS 13.5.1 (22G90)) with old java 17 versions. Here is what I encounter when trying to start the game with a recent java 17 version (17.0.8 ARM64) :

**Key Points**:

1. Mod Causing the Issue: The mod that appears to be causing the issue is WaterMedia, with version 1.3.15.
2. Exception Message: The exception message is "You are running Java on an unknown operative system."
3. Faulty Class/Method: The crash seems to occur at me.srrapero720.watermedia.Util.getOsArch(Util.java:152).

```
Caused by: java.lang.RuntimeException: You are running Java on a unknown operative system
	at me.srrapero720.watermedia.Util.getOsArch(Util.java:152) ~[watermedia-1.3.15.jar%23314!/:1.3.15]
	at me.srrapero720.watermedia.Util.<clinit>(Util.java:31) ~[watermedia-1.3.15.jar%23314!/:1.3.15]
```

[crash-2023-09-01_13.28.53-fml.txt](https://github.com/SrRapero720/watermedia/files/12497488/crash-2023-09-01_13.28.53-fml.txt)

Thank you :)

**Comment by SrRapero720** [comment]
DUPLICATED OF: #13
Please update WATERMeDIA to 1.3.42
