### ISSUE TITLE
Failed to load VLC

### ISSUE THREAD

**Issue by Yamadaisme** [WaterMediaTeam/watermedia#21]
My friend got this error when playing in the server with 
![IMG_9394](https://github.com/SrRapero720/watermedia/assets/92765169/166c7d8d-34f2-4708-b73c-8e1db8249caf)
this mod. Other player work normally

**Comment by SrRapero720** [comment]
Can you send me his logs?
located in `.minecraft/logs/latest.log`?

If for some reason he Is not with the PC... You know what Operative System Is using?

**Comment by Yamadaisme** [comment]
I told my friend to send me the log the next time he online. I will post it as soon as I got it.
And he is the only person that is using MacOS with a M2 chip. I don't know if that is the case causing that problem but I will just let you know.

**Comment by SrRapero720** [comment]
Oh, that's the problem
MacOS requieres manually install VLC (apple Silicon)

Just to know. MacOS Is not supported by WATERMeDIA at all, because *Mac Is not for play games*. But in your case he only need to install VLC. Enjoy the mod :)
