### ISSUE TITLE
Client crashes (1.12.2)

### ISSUE THREAD

**Issue by SeagalKru** [WaterMediaTeam/watermedia#23]
(Google translation from Russian)
Greetings!
After updating your mod from version 2.0.5. up to version 2.0.6. the client (1.12.2) crashes:
[crash-2023-09-23_14.26.48-client.txt](https://github.com/SrRapero720/watermedia/files/12706319/crash-2023-09-23_14.26.48-client.txt)
[latest.log](https://github.com/SrRapero720/watermedia/files/12706320/latest.log)
Thank you!

**Comment by SrRapero720** [comment]
keep using 2.0.5
i archive 2.0.6 version because it was broken

i'm gonna fix it on 2.0.7
