### ISSUE TITLE
WaterMedia 2.0.5, 2.0.7, 2.0.8 and 2.0.10 has errors

### ISSUE THREAD

**Issue by Azrien27** [WaterMediaTeam/watermedia#28]
I am using Forge 47.2.0 with the version of 1.20.1. Even though the mentioned versions of the WaterMedia states that it is compatible with the version I am using, it still shows an error that the WaterMedia version must be 1.3.33 or higher and I am definitely using a higher version than that.

But my problem is fixed when I used the version 1.3.43 for WaterMedia (no errors with this one) but I still request that this should be fixed since this may become a problem to other players using this client-side mod.

**Comment by SrRapero720** [comment]
1.3.33 or higher and below 1.4. Problem Is not WaterMedia
