### ISSUE TITLE
Incompatibility on MacOS Arm64/x64 by JNI/VLC

### ISSUE THREAD

**Issue by bastiencantet** [WaterMediaTeam/watermedia#29]
Hello, i have a problem on my mac arm.

I installed the latest version of VLC (3.0.19).
When i place a water frame (waterframe mod) that use your api, i crash

I'm using watermedia 1.3.35

A solution ?

**Comment by bastiencantet** [comment]
tested with 1.3.43 same thing

**Comment by bastiencantet** [comment]
working on 1.20.1 with same version

**Comment by SrRapero720** [comment]
i receive A LOT of reports about it, someone suggest to use a optimized JVM for Apple Silicon.
I don't know from where get it. because person who tell me that doesn't give me any link

**Comment by SrRapero720** [comment]
@TheBastosBob can you open a command-line and type `java --version`? And send me what Is the output

**Comment by GhostIsBeHere** [comment]
Hi! I'm also experiencing this problem, on an M2 mac. When I try to launch the game, it errors with "WaterMedia failed to load correctly." I am using temurin17.0.9 with x86_64 architechture. I am not using aarch/arm architecture because minecraft won't load with it. I am on Minecraft version 1.19.2 and I have tried WaterMedia 1.3.42 and 2.0.10. I hope this helps!

**Comment by SrRapero720** [comment]
@GhostIsBeHere can you join to my discord and send me a DM? i need your help to fix + enhance

**Comment by SrRapero720** [comment]
https://discord.com/cuYAzzZ

**Comment by SrRapero720** [comment]
or @TheBastosBob

**Comment by bastiencantet** [comment]
> https://discord.com/cuYAzzZ

the link not working

**Comment by bastiencantet** [comment]
About JVM,i tried multiple one because when M1 launched , there are not a lot of ARM JVM's so i began using Zulus one, i Also switeched to GraalVM one 
<img width="633" alt="Screenshot 2023-10-31 at 10 30 45" src="https://github.com/SrRapero720/watermedia/assets/43909152/26415883-f232-46bf-ba07-a9a3ced0957d">

to be sure il tried , Zulu 17 ,19 , and GraalVM 20 and i have the same problem , all are optimised for Arm

**Comment by bastiencantet** [comment]
I daily drive GraalVM

**Comment by SrRapero720** [comment]
@TheBastosBob and @GhostIsBeHere can you test with the new VLC versión (3.0.20)???

**Comment by GhostIsBeHere** [comment]
When I try to load, Watermedia claims that I do not have VLC installed on my system. I do have VLC installed on my system. Could it be perhaps getting confused because VLC is installed using homebrew?
Edit: issue persists with manual install of VLC

[Log](https://mclo.gs/8nhfNJk)

**Comment by SrRapero720** [comment]
@GhostIsBeHere your issue was you install the wrong VLC version... again
``(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), ``

**Comment by bastiencantet** [comment]
@GhostIsBeHere be careful you are using a x86_64 version of Java, maybe use arm version to have a lot of performance boost

**Comment by GhostIsBeHere** [comment]
As I stated before, minecraft won't launch on my computer with temurin17 arm builds.

**Comment by GhostIsBeHere** [comment]
> @GhostIsBeHere your issue was you install the wrong VLC version... again
> 
> ``(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), ``

Ah, thank you! I'll test this when I get back to my computer.

**Comment by bastiencantet** [comment]
@GhostIsBeHere for curiosity why temurin ?

**Comment by SrRapero720** [comment]
@GhostIsBeHere exists a universal binaries version, try using it

**Comment by bastiencantet** [comment]
or use  https://www.azul.com/downloads/#downloads-table-zulu

**Comment by GhostIsBeHere** [comment]
> @GhostIsBeHere for curiosity why temurin ?
> 
> 

Most places i've seen recommend temurin/adoptium, both minecraft and non-minecraft java. I've been meaning to look into other providers, but haven't gotten around to it.

**Comment by TheBastosBob** [comment]
@SrRapero720  `[19:07:27] [Render thread/WARN] [minecraft/ClientPacketListener]: Unknown custom packet identifier: videoplayer:network
[19:07:29] [Server thread/INFO] [co.gi.NG.wa.VideoPlayer/]: Received url: 
[19:07:35] [Render thread/WARN] [minecraft/ClientPacketListener]: Unknown custom packet identifier: videoplayer:network
[19:07:37] [Server thread/INFO] [co.gi.NG.wa.VideoPlayer/]: Received url: https://www.youtube.com/watch?v=l1J4cwD3BZg
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001066cf344, pid=15934, tid=259
#
# JRE version: OpenJDK Runtime Environment Zulu19.30+11-CA (19.0.1+10) (build 19.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM Zulu19.30+11-CA (19.0.1+10, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x553344]  jni_CallVoidMethod+0xe8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/bastiencantet/Library/Application Support/PrismLauncher/instances/1.19.2(6)/.minecraft/hs_err_pid15934.log
#
# If you would like to submit a bug report, please visit:
#   http://www.azul.com/support/
#
Process crashed with exitcode 6.
`
 still crashing for me with latest vlc version

**Comment by bastiencantet** [comment]
https://mclo.gs/7FtKUbL 

Still crashing vlc 3.0.20

**Comment by SrRapero720** [comment]
/Users/********/Library/Application Support/PrismLauncher/instances/1.19.2(6)/.minecraft/hs_err_pid15934.log

**Comment by bastiencantet** [comment]
https://mclo.gs/7Kc7Tuj
sorry

**Comment by SrRapero720** [comment]
I think JNA refuses to load (when you have ARM binaries) because it checks what arch is the JVM instead of what arch is the OS.

i am pretty sure problem was the weird conversion between ARM to x86_64 to ARM.
because binaries are 1 thing that works as a normal mac program... and needs the right architectury to work well

@GhostIsBeHere 
Try to search any way to load minecraft with the right JVM (Java version) for ARM. because i really don't want to break my head to investigate how to make it work in a weird Arch environment in a OS that i dont have it.

@TheBastosBob 
Searching about... your issue is from the JVM itself, no by VLC or any kind of... exclusivelly happens on the JVM. so probably something in your JVM is wrong.

i cannot fix this

**Comment by SrRapero720** [comment]
# STATUS OF THE ISSUE
Issue was originated on macOS (Intel or M1 or M2), jni crashes on `jni_CallVoidMethod+0x100` with no aparent reason. and was always caused when volume got changed using SimplePlayer#setVolume(int) before media was started

## POSSIBLE CAUSES/FIXES
1. Issue becomes more visible when VideoLAN releases a new update (3.0.19+), sadly i can't properly test using 3.0.18. To help with testing first is required to test latest version of [VideoLAN](https://www.videolan.org/vlc/download-macosx.html), and if it crashes using [WATERFrAMES](https://www.curseforge.com/minecraft/mc-mods/waterframes) then try downgrading to VLC 3.0.18. If wasn't present on 3.0.18 then means VLC is broken on MacOS or VLCJ bindings are broken and requires an update/fix. Versions to test are
    - [Intel x64](https://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-intel64.dmg)
    - [M1 arm64](https://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-arm64.dmg)
    - [Universal (for both)](https://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-universal.dmg)
2. JNI issue, and probably related https://github.com/java-native-access/jna/issues/1323

## WORKARROUND FOR MAC USERS
Disable all usage of VLC on mod config, waterframes includes a client-side config option to disable VLC at all located in `.minecraft/config/waterframes-client.toml`. other mods needs to do something arround it.

## JAVA 8 concerning
WATERMeDIA on MacOS was officially unsupported using JAVA 8 or Minecraft below 1.16.5, main reason was Microsoft or LWJGL wasn't interested on fix it officially on Minecraft, so i can't fix nothing.

**Comment by SrRapero720** [comment]
i close this issue because
1. i can't properly test it
2. caprica also closes the issue

if someone with the same problem and is a developer want to become into a contributor, please go to my Discord to make proper testing and (if is wanted) add you as an MacOS tester

**Comment by SrRapero720** [comment]
aparently someone fixes it using VLC 3.0.18. so... here is
https://get.videolan.org/vlc/3.0.18/macosx/vlc-3.0.18-universal.dmg

**Comment by alyip98** [comment]
Just encountered this issue on a 2023 M2 Macbook Air. Can confirm that downgrading VLC to v3.0.18 fixed it

**Comment by Stal-J** [comment]
Ran into the same issue on an M5 Macbook Air, can confirm that installing VLC v3.0.18 fixed the crash.
