### ISSUE TITLE
Failed to load vlc on watermedia 2.0.10

### ISSUE THREAD

**Issue by leonpano2006** [WaterMediaTeam/watermedia#30]
![2023-10-30_21 40 48](https://github.com/SrRapero720/watermedia/assets/58368166/60947751-6bb1-4e60-977d-e9fdec570dd7)
on minecraft 1.12.2 and ubuntu 22.04 amd64 and snap version of vlc3 installed
there is no error log about this (when it failed to load, log output have no error generated)

**Comment by leonpano2006** [comment]
and vlc logo is flashing

**Comment by leonpano2006** [comment]
and if snap version of vlc is incompatible please add infomation in https://github.com/SrRapero720/watermedia#videolan-os-support

**Comment by SrRapero720** [comment]
snap can be compatible... but probably your installation folder is different (or unknow by watermedia)
if you please, try to search where is located all your VLC binaries.
mosly using `ls -l /snap/bin` or `ls -l /var/lib/snapd/snaps`

**Comment by SrRapero720** [comment]
Snap Is not compatible. Use APT 
(Answered on discord)

**Comment by leonpano2006** [comment]
i suggest you close this as completed once you add snap vlc is not imcompatible in https://github.com/SrRapero720/watermedia#videolan-os-support

**Comment by SrRapero720** [comment]
Complete means was fixed in code and Is not longer a issue
Not planned mean bug Is not gonna get fixes.
