### ISSUE TITLE
How to play a local video use this lib?

### ISSUE THREAD

**Issue by HcFrostmorune** [WaterMediaTeam/watermedia#32]
in Minecraft 1.12.2.
I need a simple example, thx.

**Comment by SrRapero720** [comment]
There Is a issue with it. I am working on a fix

**Comment by SrRapero720** [comment]
Issue is still present
right now the only way to put a local file is with `file:///path/to/file.mp4`. whoever, watermedia breaks local file support

**Comment by CreativeMD** [comment]
Just out of curiosity, is a fix planned? People reported this issue for LittleFrames as well.

**Comment by SrRapero720** [comment]
yes, it is, but not for 2.0.x

internally, watermedia converts string to a URL by default, problem was vlc, it cannot load files using file url protocol, it requires path file for local files. main problem was UrlAPI (or url fixers). which was designed only for url but not thinking about local files, and of course i can't bring a fix without breaking things on other mods (requiring an update)

so i made the file:/// workarround until i rewrite the UrlAPI part to address local files and queue fix for 2.1.x with the other breaking changes

Also add default support to lazy shortcuts to modpack files, such as
- `local://` as equivalent of `minecraft://` on LF
- `media://` as a global path handler
- `resource://` as a jar resource path handler

All pending changes are placed on
https://github.com/users/SrRapero720/projects/3/views/1
and milestone
https://github.com/SrRapero720/watermedia/milestone/6

**Comment by SrRapero720** [comment]
@CreativeMD ^

**Comment by SrRapero720** [comment]
this issue was addressed in 2.0.27 for local files (runtime root path) using `local://`
## Usage of local
if your file is on `.minecraft/config/mymodpackfiles/intro.mp4` you should use the input `local://config/mymodpackfiles/intro.mp4`
