### ISSUE TITLE
WATERFrAMES needs a future WATERMeDIA version.

### ISSUE THREAD

**Issue by lynariel** [WaterMediaTeam/watermedia#37]
Since a long time I wanted to update WATERFrAMES but IT crashed. It was because of shader. But today I wanted to correct this problem. I removed Embeddium and occulus. (Rubbidium had the same problem) and I was able to see what was preventing the launch.

WATERFrAMES needs WATERMeDIA 2.0.24 or above to lauch.

But the last WATERMeDIA version is 2.0.23...

I'm playing in FORGE 43.3.5
Minecraft 1.19.2
[crash-2023-11-27_12.44.17-fml.txt](https://github.com/SrRapero720/watermedia/files/13473896/crash-2023-11-27_12.44.17-fml.txt)

**Comment by SrRapero720** [comment]
WATERMeDIA 2.0.24 on CurseForge is UFMR (under fucking manual review)
you need to manually download jar from Modrinth
https://modrinth.com/mod/watermedia
