### ISSUE TITLE
Failed to load VLC

### ISSUE THREAD

**Issue by TheDarknessSD** [WaterMediaTeam/watermedia#38]
[2023-11-29-7.log.gz](https://github.com/SrRapero720/watermedia/files/13506112/2023-11-29-7.log.gz)

MC 1.20.1
Forge 47.2.8

Latest Log:
[latest.log](https://github.com/SrRapero720/watermedia/files/13506123/latest.log)

**Comment by SrRapero720** [comment]
update watermedia, old rusty version
