### ISSUE TITLE
Feature Request - Jellyfin intergration 

### ISSUE THREAD

**Issue by kiritodragneel** [WaterMediaTeam/watermedia#39]
Would it be possible to add jellyfin from self hosted servers as a potential platform that is supported?
I personally host all my movie files and photos on a jellyfin server and it would be awsome to have them 
load on up in minecraft. 

An addon to this would be playlists, possibly allow me to queue multiple things or support youtube playlists

**Comment by SrRapero720** [comment]
i move your issue to watermedia. (WM is the API behind media support)
about jellyfin, i am not sure how to add suppot of it. as far i know it has an API to get file sources but not sure how to setup credentials

**Comment by SrRapero720** [comment]
for future referencies
https://api.jellyfin.org/

**Comment by SrRapero720** [comment]
I discarted the idea officially, For now i will stay away of any platform that requires login to access content (for now).
In a future maybe, but first we need to focus our man power on enhance our multimedia tech more than the network tech
