### ISSUE TITLE
1.12.2 Support: Watermedia causes SecurityExceptions

### ISSUE THREAD

**Issue by brisingraerowing** [WaterMediaTeam/watermedia#42]
Ref: LoliKingdom/LoliASM#232 (log there is similar to what I get).

2.0.24 hasn't crashed yet, still testing.

**Comment by SrRapero720** [comment]
I am aware, I have no idea why is this happening.
I'll just rewrite a lot of things on 2.1.x and pray for it works

**Comment by lSherozl** [comment]
> Ref: [LoliKingdom/LoliASM#232](https://github.com/LoliKingdom/LoliASM/issues/232) (log there is similar to what I get).
> 
> 2.0.24 hasn't crashed yet, still testing.

Hey seems there is no way to contact you on github but to message under this, you created a fix for alex mobs 1.19.2, but the issue was closed, were u able to compile the fix, if so, would you be able to send it

**Comment by SrRapero720** [comment]
Someone can please test if latest version fixes this issue?

**Comment by SrRapero720** [comment]
Minecraft 1.12.2 support is deprecated and will be removed for WM 3.0
right now i'll try to remove all the ugly code (even the bootstrap hell was done) and do a huge last maintenace and focus entirely on 3.0

if after the cleanup + maintenace stil doesn't work i will unmark 1.12.2 as a supported version as well

**Comment by SrRapero720** [comment]
1.12.2 is officially dropped for 2.0.x
if you're a developer you can try use older versions of watermedia. or fork your own WM version
NOTE: i have conditions for forks
