### ISSUE TITLE
Incompatible with Valkyrien Skies (incompatible Jackson version shaded)

### ISSUE THREAD

**Issue by brisingraerowing** [WaterMediaTeam/watermedia#43]
As per title. This mod and VS have two different Jackson versions shaded, resulting in crashes on game startup.

**Comment by SrRapero720** [comment]
jackson shaded is relocated as you can see https://github.com/SrRapero720/watermedia/blob/a2ef6053cdc48a9114fe8079c64525f15b69d646/build.gradle#L126

Any issue on VS is problem on VS

**Comment by SrRapero720** [comment]
I will rid off of many unnecesary shaded libraries just to attemp to make WaterMedia the most light possible.
Jackson too.

**Comment by SrRapero720** [comment]
Removed all unrelated dependencies (only keeping common compress+ transitive and Java-Youtube-Downloader)
