### ISSUE TITLE
Issues with VLC on Linux

### ISSUE THREAD

**Issue by xanedarel** [WaterMediaTeam/watermedia#46]
Hello there! Minecraft's logs seems to indicate the mod cannot properly locate VLC which is installed on my system, I saw on the mod's description I needed VLC3+ which is satisfied:
```
[xanedarel@voidmachine ~]$ vlc --version
VLC media player 3.0.20 Vetinari (revision 3.0.20-0-g6f0d0ab126b)
VLC version 3.0.20 Vetinari (3.0.20-0-g6f0d0ab126b)
Compiled by void-buildslave on a-fsn-de (Feb 21 2024 23:36:51)
Compiler: gcc version 13.2.0 (GCC)
```

Using either the projector or frames in WATERFrAMES trying to play : [ https://i.imgur.com/BHDopot.mp4 ] does not work producing Minecraft logs as follows : 
```
[17:34:29] [Render thread/ERROR] [watermedia/SyncMediaPlayer]: Failed to create raw player because VLC is not loaded
[17:34:29] [Render thread/WARN] [waterframes/]: Cached picture is forgotten, cleaning and reloading
[17:34:29] [Render thread/ERROR] [watermedia/API]: Founded directories but custom loading gif is missing
```
Here is what my distro's repo contains with "vlc" maybe I'm missing a package?
```
[*] libvlc-3.0.20_4                      Cross-platform multimedia player - runtime libraries
[-] phonon-qt5-backend-vlc-0.11.1_1      Phonon VLC backend for Qt5
[-] python3-vlc-3.0.20123_1              VLC bindings for python
[*] vlc-3.0.20_4                         Cross-platform multimedia player
[-] vlc-devel-3.0.20_4                   Cross-platform multimedia player - development files
[-] vlc-pause-click-plugin-1.0.0_1       Plugin for VLC that pauses/plays video on mouse click
[-] libvlc-32bit-3.0.20_4                Cross-platform multimedia player - runtime libraries (32bit)
[-] vlc-devel-32bit-3.0.20_4             Cross-platform multimedia player - development files (32bit)
[-] vlc-pause-click-plugin-32bit-1.0.0_1 Plugin for VLC that pauses/plays video on mouse click (32bit)
```
I saw on another issue page that using the nightly build of VLC might fix the issue? Thank you in advance for your time :)

**Comment by SrRapero720** [comment]
how you installed VLC?

**Comment by SrRapero720** [comment]
and where is located your VLC installation?

**Comment by xanedarel** [comment]
```
[xanedarel@voidmachine ~]$ which vlc
/usr/bin/vlc
```
I installed the VLC package from my repo, as snap is not available on my distro (or maybe it is, but I don't want to touch it). I'm currently building VLC from source to see if it works

**Comment by xanedarel** [comment]
I have reinstalled VLC from source : 
```
[xanedarel@voidmachine ~]$ which vlc
/usr/local/bin/vlc
[xanedarel@voidmachine ~]$ vlc --version
VLC media player 4.0.0-dev Otto Chriek (revision 4.0.0-dev-27996-g15902159da)
VLC version 4.0.0-dev Otto Chriek (4.0.0-dev-27996-g15902159da)
Compiled by camille on weedmachine (Mar  3 2024 21:56:55)
Compiler: gcc version 13.2.0 (GCC)
```
And Minecraft logs are still going : 
```
[22:20:18] [Render thread/ERROR] [watermedia/SyncMediaPlayer]: Failed to create raw player because VLC is not loaded
[22:20:18] [Render thread/WARN] [waterframes/]: Cached picture is forgotten, cleaning and reloading
```
Maybe my new VLC install location is wrong?

**Comment by SrRapero720** [comment]
can you send me the whole logs? using https://gist.github.com
you send me a shot of waterframes/media trying to create the player instead of the loading process

**Comment by SrRapero720** [comment]
i'll close this issue because
1. no answer
2. not a proper bug report (cutted logs)

logs doesn't contain anything sensitive to only cut the "parts you consider relevant for the modder" and thats not how it works.

**Comment by titouanlacombe** [comment]
Hello,

I had the same problem, i can't know for sure what OP problem was but mine was Flatpak sandboxing not allowing my launcher (Prism) to access the system's vlc binary.

Using the tar.gz solved the problem but its a sub optimal solution, is there a better solution?

I only see 2 potential fixes:
- Either you embed the vlc binary and its dependencies in the mod
- Or you ask Prism and every launcher to add these dependencies in their Flatpak (and other sandboxed formats) distributions

Am i missing something?

Thank you for your work, the mod is a pleasure to have ;)

**Comment by minecraftbossdj** [comment]
ive used prism flatpak before and its worked fine, its now not working for me, same error "Failed to create raw player because VLC is not loaded"
