### ISSUE TITLE
77 gbs worth of logs

### ISSUE THREAD

**Issue by footLoosely** [WaterMediaTeam/watermedia#48]
hey, there are about 77 or so gigabytes worth of logs stored in "\AppData\Local\Temp\watermedia\logs", is this intentional ?
also, thought i should add onto this, my game seems to be taking longer & longer to load every time i launch it

i think these may be related

**Comment by footLoosely** [comment]
ive deleted the 77 or so gigabytes worth of logs accrued over maybe a month of using the mod & the game now boots faster/normally

**Comment by SrRapero720** [comment]
1. you overpass the last logs record of WM
2. is not, vlc fllood logs with the picture buffer, basically your 77gb of logs are raw frame data of a video
3. is of course planned a fix

**Comment by footLoosely** [comment]
i see, thank u for responding
do u know if theres anything i can do to fix it until the fix is released ?
either way, i look forward to it : )

**Comment by SrRapero720** [comment]
Fixed, now logs are disabled by default and removed when is starting
