### ISSUE TITLE
Your Tlauncher trap is also catching ATLauncher

### ISSUE THREAD

**Issue by b0bst3r** [WaterMediaTeam/watermedia#49]
[crash-2024-03-23_13.08.03-fml.txt](https://github.com/SrRapero720/watermedia/files/14731672/crash-2024-03-23_13.08.03-fml.txt)

Whilst I totally agree with your TLauncher assessment, ATLauncher is a well respected launcher and doesn't have a sordid history of keyloggers/malware/virus background.

Any chance you can fix this?

**Comment by SrRapero720** [comment]
thanks for the report
i blame AT to have a similar name of TL, but yeah, i can fix it

in 2 days update

**Comment by TrickShow** [comment]
also SKCraftLauncher is getting caught in the same bug

**Comment by TrickShow** [comment]
Hey, you fixed this for sklauncher but not "skcraftlauncher" Could you please revise and fix. I appreciate you.

https://github.com/SKCraft/Launcher
[bootstrap.properties.txt](https://github.com/SrRapero720/watermedia/files/14831758/bootstrap.properties.txt)

**Comment by SrRapero720** [comment]
Should not
Please send me your modlist

**Comment by TrickShow** [comment]
The mod list is not needed.

Your code allows for (SKLauncher) which doesn't matter because our launcher is called (SKCraftLauncher)
Why it gets caught is because your code is looking for "tlauncher" so it catches "skcrafTLAUNCHER)

``
    public boolean tlauncher() {
        // FOLDER VALIDATION - Avoid ATLauncher and SKLauncher (for some reason)
        String f = new File("").toPath().toAbsolutePath().toString().toLowerCase();
        boolean tlauncher = f.contains("tlauncher");
        boolean atlauncher = f.contains("atlauncher");
        boolean sklauncher = f.contains("sklauncher");``

SKLauncher should be replaced with skcraftlauncher

`    public boolean tlauncher() {
        // FOLDER VALIDATION - Avoid ATLauncher and SKcraftLauncher (for some reason)
        String f = new File("").toPath().toAbsolutePath().toString().toLowerCase();
        boolean tlauncher = f.contains("tlauncher");
        boolean atlauncher = f.contains("atlauncher");
        boolean skcraftlauncher = f.contains("skcraftlauncher");`

**Comment by SrRapero720** [comment]
The Tlauncher trap needs some overhauling to avoid Non-tlauncher false-positive (and address some Tlauncher movements to Also avoid our trap)

Added on my to-do list

**Comment by captainwavez** [comment]
i'm on tlegacy (not tlauncher) and i'm getting caught by the trap, should i kill myself?

**Comment by SrRapero720** [comment]
why do you guys use so many cursed launchers 😐

**Comment by captainwavez** [comment]
i live under a bridge and im poor.

**Comment by SrRapero720** [comment]
1. this was fixed in 2.0.40
2. no support to TLegacy
