### ISSUE TITLE
[Linux] Watermedia cannot find libvlc on snap

### ISSUE THREAD

**Issue by LetterN** [WaterMediaTeam/watermedia#50]
As title suggest, it seems to only be searching `/snap/bin`, which only contains a link to the vlc program(?) `libvlc.so` is not in there but rather in `/snap/vlc/current/usr/lib`. 

doing a simple symlink to any place the mod checks fixes this issue `ln -s /snap/vlc/current/usr/lib /tmp/watermedia/videolan`

watermedia version: `2.0.28`
#46 related possibly

**Comment by SrRapero720** [comment]
Related #36
I can't find the issue when I marked it has incompatible but was far I remember I marked as incompatible because I see the snap binaries packaged in a zip-like (like APK files)

I need to do some research about because it might be easier fixed using FileUtils instead of Java IO stuff.

**Comment by SrRapero720** [comment]
fixed in 849a1d9884225a92f53b7fec817d088f622bad7c
can you test if it works?

https://github.com/SrRapero720/watermedia/releases/tag/2.0.42-pre3

**Comment by LetterN** [comment]
i reinstalled my os and vlc is installed thru the package manager now so i cannot test this unfortunately

**Comment by SrRapero720** [comment]
I'll asume is fixed
