### ISSUE TITLE
Failed to Load VLC

### ISSUE THREAD

**Issue by Animebr2222222** [WaterMediaTeam/watermedia#6]
![image](https://github.com/SrRapero720/waterframes/assets/137860983/413acddc-e389-4819-a012-88392d6e77a1)

Hi, how are you, I need help, I can't see videos because of the mod that gives me this error. I tried to look for ways to solve it, but there is no video explaining it, and apparently no one had this error like me. I'll explain how I put the video to for you to understand better I take the youtube link and put it in the top bar and save it there this image error please help me I don't know what to do and I have many plans to use waterframe

**Comment by SrRapero720** [comment]
please send me your LATEST.log file

**Comment by SrRapero720** [comment]
i transfer this issue to watermedia, waterframes is affected but problem comes from watermedia

**Comment by Animebr2222222** [comment]
thanks for answering me i dont know if this is the file but i will send you anything you let me know
[latest.log](https://github.com/SrRapero720/watermedia/files/11885124/latest.log)

**Comment by SrRapero720** [comment]
Try to
- Simplify your game directory name (remove spaces and special symbols mine '(')
- Delede `cache` directory.

**Comment by Animebr2222222** [comment]
I didn't understand very well I'm kind of slow for these things

**Comment by SrRapero720** [comment]
@Animebr2222222 i re-read your LOGS and YOU HAVE INSTALLED FancyVideo-API

PLEASE REMOVE THAT MOD, IS NOT COMPATIBLE WITH WATERMeDIA
