### ISSUE TITLE
media displays 2.0.5 requires multimedia 2.0.50, which isn't there

### ISSUE THREAD

**Issue by Greg727** [WaterMediaTeam/watermedia#69]
When will it be available?

**Comment by brisingraerowing** [comment]
As the file is available on Modrinth, I suspect Curseforge hasn't moderated the file yet. This has happened before, and the modder needed to poke the CF team to get the file approved after it sat in limbo for almost a week.

**Comment by brisingraerowing** [comment]
CF has finally approved the files.
