### ISSUE TITLE
Failed to load VLC

### ISSUE THREAD

**Issue by th0res0n** [WaterMediaTeam/watermedia#7]
Anytime on fabric that i run the /playvideo command or try to use the tv im presented with this error

![2023-06-26_13 08 16](https://github.com/SrRapero720/watermedia/assets/101760443/ddaeb441-cde8-40af-9e79-3aea43f1fe05)

this is my latest log:

[latest (13).log](https://github.com/SrRapero720/watermedia/files/11880601/latest.13.log)

**Comment by SrRapero720** [comment]
Issue by FABRIC

**Comment by SrRapero720** [comment]
No more support to FABRIC

**Comment by SrRapero720** [comment]
fixed on https://github.com/SrRapero720/watermedia/commit/e6b2ecac5dc59d8f5ec8ff87124b91dd3e67a508
