### ISSUE TITLE
Crash from the 2.0.52 version

### ISSUE THREAD

**Issue by Greg727** [WaterMediaTeam/watermedia#72]
Crash log: 
[crash-2024-05-14_23.56.43-fml.txt](https://github.com/SrRapero720/watermedia/files/15316046/crash-2024-05-14_23.56.43-fml.txt)

**Comment by SrRapero720** [comment]
fixed in the 2.0.53
- [CurseForge (UFMR)](https://www.curseforge.com/minecraft/mc-mods/watermedia/files/5344871)
- [CurseForge (direct CDN)](https://edge.forgecdn.net/files/5344/871/watermedia-2.0.53.jar)
- [Modrinth](https://modrinth.com/mod/watermedia/version/2.0.53)
