### ISSUE TITLE
[1.19.2] Game randomly freeze and crash

### ISSUE THREAD

**Issue by PinguiFabgeeklab** [WaterMediaTeam/watermedia#73]
Bug randomly, not always - When I'm teleporting or walking to some areas or randomly, there are so much lags before to freeze / crash client-side. Same problem with all people of my server (excluded 1 on MacOS).

The problem persist when i'm trying to connect to my server, i'm stuck at "Loading Terrain" and the game freeze and crash. I have sometimes to relaunch 3/4 times to connect well.

I'm suspecting some mods like WaterMedia because they take a lot of place in the logs, but not sure.

Forge 43.2.14
Minecraft 1.19.2
![modlist](https://github.com/SrRapero720/watermedia/assets/78692586/bd49396a-b07a-4688-ad16-4e95b4f70d8d)
[debug(3).log](https://github.com/SrRapero720/watermedia/files/15380801/debug.3.log)

**Comment by SrRapero720** [comment]
i only know 3 things
1. for some STUPID REASON vlc is begin called to parse a damn PNG file instead of use the ImageRenderer
2. embeddium is triggering something else that causes VLC begin dramatic and die
3. your issue sounds like a damn deadlock :/

**Comment by SrRapero720** [comment]
closed due to inactivity, i am working on v3 so i hpe this get fixed  (if is happening yet)
