### ISSUE TITLE
NeoForge 1.20.4?

### ISSUE THREAD

**Issue by snowleopardd** [WaterMediaTeam/watermedia#76]
Hey, i was wondering if there's gonna be support for neoforge 1.20.4? seems like a stable version.

**Comment by SrRapero720** [comment]
is still planned but neoforge isn't making it easy. every update is breaking things (and broken things isn't funny)
probably we will add neoforge support for the 1.21

**Comment by SrRapero720** [comment]
NeoForge support was finally added for 1.21
1.20.x is not supported
