### ISSUE TITLE
trying to play on steam deck. vlc not loaded

### ISSUE THREAD

**Issue by MonsieurMonke** [WaterMediaTeam/watermedia#77]
im trying to use watermedia but whenever i try and use it i get "vlc failed to load. this is not normal behavior etc..."

i am assuming it has something to do with the immutable filesystem or that it has to have vlc installed via flatpack that the mod is looking for vlc in a directory where vlc is not in or something
[Text_File.txt](https://github.com/SrRapero720/watermedia/files/15457555/Text_File.txt)
attached the log from prism launcher i dunno if that helps. 

i just need to know how i could fix this or if it can be fixed at all.

**Comment by SrRapero720** [comment]
Flatpak is not supported or even Pakman. please use `apt-get` instead. Flatpak uses a sandbox FS and pakman _have an history of works whenever it want_

**Comment by MonsieurMonke** [comment]
Unfortunately, since steam-os is based on arch Linux, Apt is not an option. It appears getting the mod to work on steam deck is not possible unless the mod itself changes. Or I install a different OS on my steam deck.

**Comment by Xeddius** [comment]
> Flatpak is not supported or even Pakman. please use `apt-get` instead. Flatpak uses a sandbox FS and pakman _have an history of works whenever it want_

@SrRapero720 

I can use Flatseal and in under a minute fix all permissions so both minecraft and vlc can see each other, can you please add a simple configuration option so we can just manually set the location of the VLC binaries? This would solve the entire issue for most if not all linux users.

I too am trying to use it on steam deck and I'm surprised nobody has suggested just adding the ability to manually specify the location.

I'll even write the documentation for Linux users so you can just link them to a FAQ for how to set it up on their specific Linux systems.
