### ISSUE TITLE
[NetworkAPI]: Google Drive Videos doesn't working

### ISSUE THREAD

**Issue by Queso924** [WaterMediaTeam/watermedia#78]
I tried it once and it worked, but then it gives an error and says "could not download image"

**Comment by SrRapero720** [comment]
This needs better documentation

**Comment by SrRapero720** [comment]
For more context i made an announce on discord
![image](https://github.com/WaterMediaTeam/watermedia/assets/29090346/da53b3e3-d3dc-4655-beda-8de6ccd032eb)
