### ISSUE TITLE
I ran into a problem when using a water frames.

### ISSUE THREAD

**Issue by ilikebackrooms** [WaterMediaTeam/watermedia#82]
This happened when I was using Minecraft's water frames MOD.

**Comment by SrRapero720** [comment]
# 🗃️ I NEED YOUR LOGS TO DIAGNOSE
Your latest.log file is placed in your ``.minecraft/logs`` folder (instance folder), pickup the file and upload it into any website below. 
If your game crashes please also append the crash report in the ``.minecraft/crash-report`` folder.
Paste it here so i can help you more easier

# 🖥️ PASTE PAGES
- **Github (100MB)**: https://gist.github.com/
- **MCLogs (10MB)**: https://mclo.gs/
- **PasteGG (15MB)**: https://paste.gg/
- **PasteEE (1MB)**: https://paste.ee/
- **HasteBin (400kB)**: https://hastebin.com/
- **CentOS (1MB)**: https://paste.centos.org/
