### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by RoyalOughtness** [WaterMediaTeam/watermedia#86]
Repo is missing a license file, making it unclear

**Comment by SrRapero720** [comment]
WaterMedia source code is All Rights Reserved, except VLCJ module which is unser the same upstream license.

**Comment by SrRapero720** [comment]
We're planning to move to other license, but that after finish our v3 development

**Comment by caprica** [comment]
> WaterMedia source code is All Rights Reserved, except VLCJ module which is unser the same upstream license.

I don't know what you're trying to say here about vlcj being under "the same upstream license", but for the avoidance of any doubt for anyone reading this issue, vlcj is licensed only under GPL 3 or later, or a paid commercial license if you want to avoid GPL.

**Comment by SrRapero720** [comment]
@caprica 
watermedia development was a little bit caotic. not just licences thing also on how to do the API.
so yeah i am not very happy about have multiple modules under X/Y license.

thanks for the reminder i updated #51. But i think i need to talk more about this on DMs.
