### ISSUE TITLE
Volume cannot be changed on macOS

### ISSUE THREAD

**Issue by andriihorpenko** [WaterMediaTeam/watermedia#88]
Since 2.0.64 update, volume controls in WATERFRaMES are inoperable, and volume is always at max level. Changing volume inside frames, as well as Minecraft volume settings, have no effect. The only way to reduce volume is to change machine's system volume itself.

Minecraft version: 1.20.1
WATEFRaMES version: 2.0.10
WATERMeDIA version: 2.0.65
macOS version: Sonoma 14.5
Chip: M1 Max

**Comment by SrRapero720** [comment]
Attemping to fix a macos issue i caused another
Fix in the next days

**Comment by andriihorpenko** [comment]
The issue was fixed is some recent update.
