### ISSUE TITLE
YouTube not working for streams and videos

### ISSUE THREAD

**Issue by joveaaron** [WaterMediaTeam/watermedia#92]
Title. Paste live link as youtube.com/live/(Live ID) indicates "Image could not be downloaded" and youtube.com/watch?v=(Live ID) indicates it's ok but picture is black.
Is it not planned or you haven't though of it?

**Comment by SrRapero720** [comment]
streams are supported, if aren't working now means youtube is doing changes (damn again)
we're look into it, but fix will be queue for v3

**Comment by AzzyDR** [comment]
google drive is now not working for some files

**Comment by SrRapero720** [comment]
_must b fixed_
