### ISSUE TITLE
TLauncher ≠ TL Legacy

### ISSUE THREAD

**Issue by Lambdasond** [WaterMediaTeam/watermedia#94]
Watermedia does not work on TLauncher, because it is a program with closed source code and viruses. But there is still TL Legacy, which has open source code and without viruses (TLauncher **was made** on TL Legacy). 

Perhaps it would be possible to access the mod with TL Legacy.

**Comment by SrRapero720** [comment]
TLegacy identifies internally itself as TLauncher, what i am supposted to do?
