### ISSUE TITLE
Tlauncher issues when using the basic Minecraft Launcher

### ISSUE THREAD

**Issue by DreamLaLune** [WaterMediaTeam/watermedia#98]
as you decided to make the mod recognize if we are using Tlauncher (things that i respect cause it is a really bad launcher)
you make it recognize also Mincraftlauncher (there's is also tlauncher in it)
would you be able to fix it ? i dont wanna use SKlauncher or MultiMC, just the basic minecraft launcher

**Comment by SrRapero720** [comment]
i will do a way better detector...

**Comment by DreamLaLune** [comment]
is it coming ? i know you do not have only this project, but im not the only one to get the issues

**Comment by SrRapero720** [comment]
i... was... trying to avoid work on 2.0.x anymore, i am focusing on v3 but yeah this is forcing me really a lot

**Comment by SrRapero720** [comment]
fixed on latest release

**Comment by DreamLaLune** [comment]
works perfectly, thank you so much for this update
