### ISSUE TITLE
Watermedia cannot find vlc on linux

### ISSUE THREAD

**Issue by OpalSoPL** [WaterMediaTeam/watermedia#99]
Minecraft Version: 1.20.1
Watermedia Version: 2.0.70
Log: https://gist.github.com/OpalSoPL/4f20fb1b24ccd4960e45f8f2a7d3c3c3
VLC version: 3.0.16 (from apt) 
OS: Linux Mint 21.3 (x64)

VLC bin is in /usr/bin/vlc

**Comment by OpalSoPL** [comment]
Ok, that was related to the launcher from flatpak

**Comment by SrRapero720** [comment]
lovely flatpak
lovely linux
